account_main.o, account_main.sei: account_main.sec \
 /home/qrs/opt/modelverify/include/ts/ts.h \
 /home/qrs/opt/modelverify/include/utils/sec.h \
 /home/qrs/opt/modelverify/include/utils/boolean.h \
 /home/qrs/opt/modelverify/include/utils/assertion.h \
 /home/qrs/opt/modelverify/include/ts/generated.h \
 /home/qrs/opt/modelverify/include/ts/convex.h \
 /home/qrs/opt/modelverify/include/atl/string.h \
 /home/qrs/opt/modelverify/include/atl/object.h \
 /home/qrs/opt/modelverify/include/ts/timemark.h \
 /home/qrs/opt/modelverify/include/utils/stdint.h \
 /home/qrs/opt/modelverify/include/ts/register.h \
 /home/qrs/opt/modelverify/include/ts/engine.h \
 /home/qrs/opt/modelverify/include/ts/dfsm.h \
 /home/qrs/opt/modelverify/include/ts/scenario.h \
 /home/qrs/opt/modelverify/include/ts/ndfsm.h \
 /home/qrs/opt/modelverify/include/atl/unit.h \
 /home/qrs/opt/modelverify/include/c_tracer/c_tracer.h \
 /home/qrs/opt/modelverify/include/ts/coverage.h \
 /home/qrs/opt/modelverify/include/ts/version.hh account_scenario.seh
